repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgres
    chart: bitnami/postgresql-ha
    version: 3.2.6

  - name: adminer
    chart: ./charts/app
    values:
      - ./values/adminer.yaml

  - name: kanban-app
    chart: ./charts/app
    values:
      - ./values/kanban-app.yaml

  - name: kanban-ui
    chart: ./charts/app
    values:
      - ./values/kanban-ui.yaml

  - name: ingress-backend
    chart: stable/nginx-ingress
    version: 1.36.0

  - name: ingress-controller
    chart: ./charts/ingress
    values:
      - ./values/ingress.yaml
