apiVersion: v2
name: ingress
description: A Helm chart for Ingress Controller
type: application
version: 0.1.0
appVersion: 1.16.0
keywords:
  - ingress
  - nginx
  - api-gateway
home: https://github.com/shahmeetk/helmDemo
maintainers:
  - name: Meet Shah
    url: https://github.com/shahmeetk
